name: Commit Author CI

on:
  pull_request:
  push:
jobs:
  check-commits-authors:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - name: "Checking commits authors email domain"
      uses: semcelik/commit-author-action@master
      with:
        email_domain: 'profusion.mobi'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        error_on_fail: 'true'
  